
const ConstantsConnection = {
    //ACTIONS
    CONNECTION_DISCONNECT: 'CONNECTION_DISCONNECT',
    CONNECTION_CONNECT: 'CONNECTION_CONNECT',
    CONNECTION_TEST: 'CONNECTION_TEST',

    //STATES
    CONNECTION_DISCONNECTED: 'CONNECTION_DISCONNECTED',
    CONNECTION_CONNECTED: 'CONNECTION_CONNECTED',

    //RESPONSES
    CONNECTION_CONNECT_SUCCESSFUL: 'CONNECTION_CONNECT_SUCCESSFUL',
    CONNECTION_CONNECT_FAILURE: 'CONNECTION_CONNECT_FAILURE',
    CONNECTION_DISCONNECT_SUCCESSFUL: 'CONNECTION_DISCONNECT_SUCCESSFUL',
    CONNECTION_DISCONNECT_FAILURE: 'CONNECTION_DISCONNECT_FAILURE',
    CONNECTION_TEST_SUCCESSFUL: 'CONNECTION_TEST_SUCCESSFUL',
    CONNECTION_TEST_FAILURE: 'CONNECTION_TEST_FAILURE',
    CONNECTION_NO_RESPONSE: 'CONNECTION_NO_RESPONSE'
};

export default ConstantsConnection;