
const ConstantsEventCommand = {

    INSTANCE_SELECT: "INSTANCE_SELECT",
    INSTANCE_ADD: "INSTANCE_ADD",
    INSTANCE_REMOVE: "INSTANCE_REMOVE",

    ACCOUNT_SELECT: "ACCOUNT_SELECT",
    ACCOUNT_LOGIN: "ACCOUNT_LOGIN",
    ACCOUNT_LOGOUT: "ACCOUNT_LOGOUT",

    SCRIPT_SELECT: "SCRIPT_SELECT",
    SCRIPT_START: "SCRIPT_START",
    SCRIPT_PAUSE: "SCRIPT_PAUSE",
    SCRIPT_STOP: "SCRIPT_STOP"

};

export default ConstantsEventCommand;