const ConstantsInstance = {
    //ACTIONS
    INSTANCE_SELECTING: 'INSTANCE_SELECTING',
    INSTANCE_SELECTED: 'INSTANCE_SELECTED',
    INSTANCE_ADDING: 'INSTANCE_ADDING',
    INSTANCE_ADDED: 'INSTANCE_ADDED',
    INSTANCE_REMOVING: 'INSTANCE_REMOVING',
    INSTANCE_REMOVED: 'INSTANCE_REMOVED',
    INSTANCE_RESET: 'INSTANCE_RESET',

    INSTANCE_SCRIPT_SELECTING: 'INSTANCE_SCRIPT_SELECTING',
    INSTANCE_SCRIPT_SELECTED: 'INSTANCE_SCRIPT_SELECTED',
    INSTANCE_SCRIPT_STARTING: 'INSTANCE_SCRIPT_STARTING',
    INSTANCE_SCRIPT_STARTED: 'INSTANCE_SCRIPT_STARTED',
    INSTANCE_SCRIPT_PAUSING: 'INSTANCE_SCRIPT_PAUSING',
    INSTANCE_SCRIPT_PAUSED: 'INSTANCE_SCRIPT_PAUSED',
    INSTANCE_SCRIPT_STOPPING: 'INSTANCE_SCRIPT_STOPPING',
    INSTANCE_SCRIPT_STOPPED: 'INSTANCE_SCRIPT_STOPPED',

    INSTANCE_ACCOUNT_SELECTING: 'INSTANCE_ACCOUNT_SELECTING',
    INSTANCE_ACCOUNT_SELECTED: 'INSTANCE_ACCOUNT_SELECTED',
    INSTANCE_ACCOUNT_LOGGING_IN: 'INSTANCE_ACCOUNT_LOGGING_IN',
    INSTANCE_ACCOUNT_LOGGED_IN: 'INSTANCE_ACCOUNT_LOGGED_IN',
    INSTANCE_ACCOUNT_LOGGING_OUT: 'INSTANCE_ACCOUNT_LOGGING_OUT',
    INSTANCE_ACCOUNT_LOGGED_OUT: 'INSTANCE_ACCOUNT_LOGGED_OUT'
};

export default ConstantsInstance;